<?php

namespace Ebay\Sell\Metadata\Model;

use OpenAPI\Runtime\AbstractModel as AbstractModel;

/**
 * This is the response object returned by a call to getProductAdoptionPolicies.
 */
class ProductAdoptionPolicyResponse extends AbstractModel
{
    /**
     * A list of category IDs from the marketplace specified in the request where each
     * returned element represents a leaf node in the category tree. Each element in
     * the list contains the policies governing whether or not items listed in that
     * category must include an ePID value (which links the item to the eBay Catalog).
     *
     * @var \Ebay\Sell\Metadata\Model\ProductAdoptionPolicy[]
     */
    public $productAdoptionPolicies = null;

    /**
     * A list of the warnings that were generated as a result of the request. This
     * field is not returned if no warnings were generated by the request.
     *
     * @var \Ebay\Sell\Metadata\Model\Error[]
     */
    public $warnings = null;
}
